export const tableHeaders = [
    "Sr No.",
    "Heading 1",
    "Heading 2",
    "Heading 3",
    "Heading 4",
    "Heading 5",
    "Heading 6"
];

export const tableItemsData = [
    {
        serialNo: 1,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 2,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 3,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 4,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 5,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 6,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 7,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 8,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 9,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 10,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 11,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    },
    {
        serialNo: 12,
        firstItem: "Item",
        secondItem: "Item",
        thirdItem: "Item",
        fourthItem: "Item",
        fifthItem: "Item",
        sixthItem: "Item",
    }
]
